### PR TITLE
Copy objects

### PR DESCRIPTION
**Pull request by jmdeon**

### CODE REVIEW

**Comment by stevoleeto** [comment]
need someone else to check if feature where blocks are disabled are putting them all on the answer pane is working still or not. From my initial testing it appears to not be working.

**Comment by jmdeon** [comment]
@stevoleeto it works for me locally.

**Comment by stevoleeto** [comment]
@sguthals can you try this on yours? I

**Comment by stevoleeto** [comment]
This needs to be reopned but we figured it out. The logic for blocking out blocks only works for students.

**Comment by jmdeon** [comment]
But that's not a symptom of the changes on this branch, so this branch is still good to be merged.

**Comment by sguthals** [comment]
merged

--

Sarah Guthals, PhD
GitHub Independent Contractor
Forbes 30 Under 30: Science
sguthals@github.com

**Pull request closed without merging**
