### PR TITLE
feedback is given immediately to a submitted answer for a question

### PR DESCRIPTION
**Pull request by stevoleeto**
Feedback (correct / incorrect answer) is given when someone submits an answer to a question. 

Feedback is given immediately in the front end (JavaScript), meaning the submitted answer still needs to be verified and saved in the backend.

### CODE REVIEW

**Comment by jmdeon** [comment]
@stevoleeto Hey could this be done by checking the @check variable when rendering check.js.erb? Look at line 248 of questions_controller.js. Cause adding this means doing another encoding of the answer when its already going to be encoded and checked elsewhere. 

If you agree I can make the change because I'm working in those files right now for logging student attempts.

**Comment by stevoleeto** [comment]
Yeah that would work. It also could be done all server side and just use a flash to alert the user. But at some point there may be detailed feedback (highlight bad blocks, show how close it is to the right answer, tips, etc) and I'm not sure if that would be better suited for front end logic or backend. 

I opt'd for front end because it could be slightly computational but I'm not sure. Something to consider.

**Comment by jmdeon** [comment]
Yeah my point is that its already being done (questions_controller) so computationally it would be just add a boolean check on front-end.

**Comment by stevoleeto** [comment]
Yeah I meant the detailed feedback, where would that be best suited for.

**Comment by jmdeon** [comment]
Lets switch to slack to talk about detailed feedback. For now I'm asking should this pull request for immediate feedback be changed to a simple check of the @check variable?

**Comment by stevoleeto** [comment]
Yeah for this current iteration that makes more sense so let's do that. Also maybe remove the answer since it's not needed from check.js.erb - right?

**Comment by jmdeon** [comment]
Yeah its not needed.

**Pull request merged**
